/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartfashionshop;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author waths
 */
public class AllCustomerReports extends javax.swing.JFrame {

    /**
     * Creates new form AllCustomerReports
     */
    public AllCustomerReports() {
        initComponents();
        DefaultTableModel dtm=(DefaultTableModel)allCustomerReportstable.getModel();
        String[] numbertemp1 = new String[0];
        double[] amounttemp1 = new double[0];

        L1:
        for (int i = 0; i < DBconnection.getDBConnection().getOrderList().size(); i++) {
            for (int j = 0; j < numbertemp1.length; j++) {
                if (DBconnection.getDBConnection().getOrderList().get(i).getCustomerId().equals(numbertemp1[j])) {
                    amounttemp1[j] += DBconnection.getDBConnection().getOrderList().get(i).getAmount();
                    continue L1;
                }
            }
            numbertemp1 = Controller.extendArray1(numbertemp1);
            numbertemp1[numbertemp1.length - 1] = DBconnection.getDBConnection().getOrderList().get(i).getCustomerId();
            amounttemp1 = Controller.extendArray1(amounttemp1);
            amounttemp1[amounttemp1.length - 1] = DBconnection.getDBConnection().getOrderList().get(i).getAmount();
        }
        dtm.setRowCount(0);
        L2:for (int l = 0; l < numbertemp1.length; l++) {
            int[] qtytemp1 = new int[6];
            
            for (int k = 0; k < DBconnection.getDBConnection().getOrderList().size(); k++) {
                if (numbertemp1[l].equals(DBconnection.getDBConnection().getOrderList().get(k).getCustomerId())) {
                    if (DBconnection.getDBConnection().getOrderList().get(k).getSize().equals("xs")) {
                        qtytemp1[0] +=DBconnection.getDBConnection().getOrderList().get(k).getQty();
                    } else if (DBconnection.getDBConnection().getOrderList().get(k).getSize().equals("s")) {
                        qtytemp1[1] += DBconnection.getDBConnection().getOrderList().get(k).getQty();
                    } else if (DBconnection.getDBConnection().getOrderList().get(k).getSize().equals("m")) {
                        qtytemp1[2] += DBconnection.getDBConnection().getOrderList().get(k).getQty();
                    } else if (DBconnection.getDBConnection().getOrderList().get(k).getSize().equals("l")) {
                        qtytemp1[3] += DBconnection.getDBConnection().getOrderList().get(k).getQty();
                    } else if (DBconnection.getDBConnection().getOrderList().get(k).getSize().equals("xl")) {
                        qtytemp1[4] += DBconnection.getDBConnection().getOrderList().get(k).getQty();
                    } else if (DBconnection.getDBConnection().getOrderList().get(k).getSize().equals("xxl")) {
                        qtytemp1[5] += DBconnection.getDBConnection().getOrderList().get(k).getQty();
                    }

                }
            }

            Object[] data = {numbertemp1[l], qtytemp1[0], qtytemp1[1], qtytemp1[2], qtytemp1[3], qtytemp1[4], qtytemp1[5], amounttemp1[l]};
            dtm.addRow(data);

        }
        allCustomerReportstable.setRowHeight(40);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        allCustomerReportstable = new javax.swing.JTable();
        Backbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        allCustomerReportstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Id", "XS", "S", "m", "L", "xl", "xxl", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(allCustomerReportstable);

        Backbutton.setBackground(new java.awt.Color(153, 0, 51));
        Backbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Backbutton.setForeground(new java.awt.Color(255, 255, 255));
        Backbutton.setText("Back");
        Backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Backbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbuttonActionPerformed
                        AllCustomerReports.this.dispose();
			new ViewForm().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BackbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllCustomerReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllCustomerReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbutton;
    private javax.swing.JTable allCustomerReportstable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    static class setVisible {

        public setVisible(boolean b) {
        }
    }
}
