package smartfashionshop;


//import com.oracle.webservices.internal.api.databinding.DatabindingModeFeature;
import smartfashionshop.HomeTab;
import javax.swing.JOptionPane;
import smartfashionshop.Controller;
import smartfashionshop.Orders;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author waths
 */
public class PlaceOrder extends javax.swing.JFrame {

    /**
     * Creates new form PlaceOrder
     */
    public PlaceOrder() {
        initComponents();
        lblOrderidtxt.setText(Controller.generateId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        orderidbutton = new javax.swing.JLabel();
        sizeButton = new javax.swing.JLabel();
        qtybutton = new javax.swing.JLabel();
        amountButton = new javax.swing.JLabel();
        customeridbutton = new javax.swing.JLabel();
        customerIdtextField = new javax.swing.JTextField();
        sizetextField = new javax.swing.JTextField();
        qtytextField = new javax.swing.JTextField();
        placeButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        amountlabel = new javax.swing.JLabel();
        lblOrderidtxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backButton.setBackground(new java.awt.Color(153, 0, 51));
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        orderidbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderidbutton.setText("Order Id :");

        sizeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sizeButton.setText("size :");

        qtybutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qtybutton.setText("QTY :");

        amountButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        amountButton.setText("Amount : ");

        customeridbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        customeridbutton.setText("Customer ID :");

        qtytextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                qtytextFieldMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                qtytextFieldMouseReleased(evt);
            }
        });
        qtytextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtytextFieldActionPerformed(evt);
            }
        });

        placeButton.setBackground(new java.awt.Color(0, 153, 153));
        placeButton.setForeground(new java.awt.Color(255, 255, 255));
        placeButton.setText("Place");
        placeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                placeButtonMouseEntered(evt);
            }
        });
        placeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placeButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("(XS/S/M/L/XXL)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(placeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(customeridbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(orderidbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sizeButton)
                            .addComponent(qtybutton)
                            .addComponent(amountButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(amountlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 95, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblOrderidtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(customerIdtextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sizetextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(qtytextField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderidbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblOrderidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customeridbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(customerIdtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sizeButton)
                    .addComponent(sizetextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtybutton)
                    .addComponent(qtytextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(amountButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(amountlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)))
                .addGap(30, 30, 30)
                .addComponent(placeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void placeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placeButtonActionPerformed
        String orderId = lblOrderidtxt.getText();
        String customerId = customerIdtextField.getText();
        String Size = sizetextField.getText();
        int qty = Integer.parseInt(qtytextField.getText());
        double amount = Double.parseDouble(amountlabel.getText());
            System.out.println(orderId);
        Orders orders = new Orders(orderId, customerId, Size, qty, amount);
        System.out.println(orders.getOrderId()+", "+orders.getCustomerId());
        //System.out.println(DBconnection.getDBConnection().getOrderList().get(1).getOrderId());
        //Orders order;
        boolean addOrder = Controller.addOrder(orders);

        if (addOrder==true) {

            JOptionPane.showMessageDialog(PlaceOrder.this, "Order Placed..!");
              //System.out.println(DBconnection.getDBConnection().getOrderList().get(1).getCustomerId());
        }
      
    }//GEN-LAST:event_placeButtonActionPerformed

    private void qtytextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtytextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtytextFieldActionPerformed

    private void qtytextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtytextFieldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_qtytextFieldMouseClicked

    private void qtytextFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_qtytextFieldMouseReleased
        // TODO aplaceButton.addMouseListener(new MouseAdapter() {


    }//GEN-LAST:event_qtytextFieldMouseReleased

    private void placeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_placeButtonMouseEntered
        // TODO add your handling code here:
        int amo = Controller.amount(sizetextField.getText(), qtytextField.getText());
        amountlabel.setText(String.valueOf(amo));
    }//GEN-LAST:event_placeButtonMouseEntered

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
                PlaceOrder.this.dispose();
			new HomeTab().setVisible(true);
       
	   
	
		        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaceOrder.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PlaceOrder().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountButton;
    private javax.swing.JLabel amountlabel;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField customerIdtextField;
    private javax.swing.JLabel customeridbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblOrderidtxt;
    private javax.swing.JLabel orderidbutton;
    private javax.swing.JButton placeButton;
    private javax.swing.JLabel qtybutton;
    private javax.swing.JTextField qtytextField;
    private javax.swing.JLabel sizeButton;
    private javax.swing.JTextField sizetextField;
    // End of variables declaration//GEN-END:variables

}
