/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartfashionshop;

/**
 *
 * @author waths
 */
public class ViewForm extends javax.swing.JFrame {

    /**
     * Creates new form ViewForm
     */
    public ViewForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBTN = new javax.swing.JButton();
        viewCustomerBTN = new javax.swing.JButton();
        BestInCustomersBTN = new javax.swing.JButton();
        AllCustomersBtn = new javax.swing.JButton();
        categorryByQTYbutton = new javax.swing.JButton();
        categoryByAmountButton = new javax.swing.JButton();
        OrdersByAmountButton = new javax.swing.JButton();
        AllOdersButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBTN.setBackground(new java.awt.Color(153, 0, 51));
        backBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backBTN.setForeground(new java.awt.Color(255, 255, 255));
        backBTN.setText("Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        viewCustomerBTN.setBackground(new java.awt.Color(0, 153, 153));
        viewCustomerBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewCustomerBTN.setForeground(new java.awt.Color(255, 255, 255));
        viewCustomerBTN.setText("View Customers");
        viewCustomerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomerBTNActionPerformed(evt);
            }
        });

        BestInCustomersBTN.setBackground(new java.awt.Color(0, 153, 153));
        BestInCustomersBTN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BestInCustomersBTN.setForeground(new java.awt.Color(255, 255, 255));
        BestInCustomersBTN.setText("Best Customers");
        BestInCustomersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestInCustomersBTNActionPerformed(evt);
            }
        });

        AllCustomersBtn.setBackground(new java.awt.Color(0, 153, 153));
        AllCustomersBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AllCustomersBtn.setForeground(new java.awt.Color(255, 255, 255));
        AllCustomersBtn.setText("All Customers");
        AllCustomersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllCustomersBtnActionPerformed(evt);
            }
        });

        categorryByQTYbutton.setBackground(new java.awt.Color(102, 0, 102));
        categorryByQTYbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        categorryByQTYbutton.setForeground(new java.awt.Color(255, 255, 255));
        categorryByQTYbutton.setText("Categorized QTY");
        categorryByQTYbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorryByQTYbuttonActionPerformed(evt);
            }
        });

        categoryByAmountButton.setBackground(new java.awt.Color(102, 0, 102));
        categoryByAmountButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        categoryByAmountButton.setForeground(new java.awt.Color(255, 255, 255));
        categoryByAmountButton.setText("Categorized By Amount");
        categoryByAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryByAmountButtonActionPerformed(evt);
            }
        });

        OrdersByAmountButton.setBackground(new java.awt.Color(102, 102, 102));
        OrdersByAmountButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        OrdersByAmountButton.setForeground(new java.awt.Color(255, 255, 255));
        OrdersByAmountButton.setText("Orders By Amount");
        OrdersByAmountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersByAmountButtonActionPerformed(evt);
            }
        });

        AllOdersButton.setBackground(new java.awt.Color(102, 102, 102));
        AllOdersButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AllOdersButton.setForeground(new java.awt.Color(255, 255, 255));
        AllOdersButton.setText("All Orders");
        AllOdersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllOdersButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(categorryByQTYbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryByAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AllOdersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OrdersByAmountButton, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BestInCustomersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCustomerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AllCustomersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(viewCustomerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categorryByQTYbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OrdersByAmountButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(BestInCustomersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AllOdersButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(categoryByAmountButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AllCustomersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        ViewForm.this.dispose();
        new HomeTab().setVisible(true);            // TODO add your handling code here:
    }//GEN-LAST:event_backBTNActionPerformed

    private void viewCustomerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerBTNActionPerformed
        ViewForm.this.dispose();
        new ViewCustomer().setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_viewCustomerBTNActionPerformed

    private void BestInCustomersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestInCustomersBTNActionPerformed
                 ViewForm.this.dispose();
                new BestInCustomer().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_BestInCustomersBTNActionPerformed

    private void AllCustomersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllCustomersBtnActionPerformed
                ViewForm.this.dispose();
                new AllCustomerReports().setVisible(true);           // TODO add your handling code here:
    }//GEN-LAST:event_AllCustomersBtnActionPerformed

    private void categorryByQTYbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorryByQTYbuttonActionPerformed
                ViewForm.this.dispose();
                new SorteByQuantity().setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_categorryByQTYbuttonActionPerformed

    private void categoryByAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryByAmountButtonActionPerformed
                ViewForm.this.dispose();
                new sortedByAmount().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_categoryByAmountButtonActionPerformed

    private void OrdersByAmountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersByAmountButtonActionPerformed
                     ViewForm.this.dispose();
                     new OrderByAmount().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_OrdersByAmountButtonActionPerformed

    private void AllOdersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllOdersButtonActionPerformed
                ViewForm.this.dispose();
                new AllOrders().setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_AllOdersButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllCustomersBtn;
    private javax.swing.JButton AllOdersButton;
    private javax.swing.JButton BestInCustomersBTN;
    private javax.swing.JButton OrdersByAmountButton;
    private javax.swing.JButton backBTN;
    private javax.swing.JButton categorryByQTYbutton;
    private javax.swing.JButton categoryByAmountButton;
    private javax.swing.JButton viewCustomerBTN;
    // End of variables declaration//GEN-END:variables
}
